#
# Makefile for Pascal-p5 using IP Pascal
#
# Makes the main compiler interpreter settings.
#
all: pascals

pascals: source\pascals.pas
	pc source\pascals.pas/nrf
	mv source\pascals.exe bin
	
clean:
	find . -name "*.out" -type f -delete
	find . -name "*.lst" -type f -delete
	find . -name "*.obj" -type f -delete
	find . -name "*.sym" -type f -delete
	find . -name "*.int" -type f -delete
	find . -name "*.dif" -type f -delete
	find . -name "*.err" -type f -delete
	find . -name "*.tmp" -type f -delete
	find . -name "prd" -type f -delete
	find . -name "prr" -type f -delete
	find . -name "temp" -type f -delete
	find . -name "tmp" -type f -delete
	find . -name "*~" -type f -delete
